services:
  db:
    # ./mysql-init MySQLコンテナが初めて起動した瞬間に実行される
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/rails/public:ro
  web:
    #- rails_storage:/rails/storageにすると表示されなくなる
    volumes:
      - .:/rails
      - rails_storage:/app/storage
    environment:
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
  worker:
    volumes:
      - .:/rails
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
volumes:
  db_data:
  rails_storage:

# docker compose upで起動