services:
  web:
    build: .
    volumes:
      - rails_storage:/rails/storage
    environment:
      REDIS_URL: redis://redis:6379/1
      DB_HOST: aws-rds.c524yg4yi2ju.ap-northeast-1.rds.amazonaws.com

  worker:
    environment:
      REDIS_URL: redis://redis:6379/1
      DB_HOST: aws-rds.c524yg4yi2ju.ap-northeast-1.rds.amazonaws.com

volumes:
  rails_storage:


# RAILS_ENV=production docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
