development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: original_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: original_production
