development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: original_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: original_production
