default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>

production:
  <<: *default
  database: rails_db_production
  pool: 20

development:
  <<: *default
  database: original_development
  pool: 5

test:
  <<: *default
  database: original_test
  pool: 5