default: &default
  # RubyでMySQLを扱うためのライブラリ名
  adapter: mysql2
  encoding: utf8mb4
  # 接続先
  host: <%= ENV.fetch("DATABASE_HOST")%>
  # 一般ユーザー設定
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  # 起動時に自動作成するDB名

production:
  <<: *default
  database: rails_db_production
  pool: 20

development:
  <<: *default
  # 起動時に自動作成するDB名
  database: original_development
  pool: 5

test:
  <<: *default
  database: original_test
  pool: 5