default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_DEVELOPMENT") %>

test:
  <<: *default
  database: original_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_PRODUCTION") %>
